### PR TITLE
Moving JS to NPM & simplify JS

### LINKED ISSUE #6: Switch to npm/yarn for JS dependencies
JS dependencies are now included from CDN and a script is included to download JS dependencies from locally(?)
I there a reason not to use npm/yarn for managing JS dependencies? (PR coming up)

### PR DESCRIPTION
**Pull request by micschk**
This PR (fixes #6):
- Replaces 9 separate CDN JS files with one 157 KiB local file
- Removes the PHP Require() function (JS/CSS included via Yaml config instead)
- Introduces SimplerSilverstripe as a composer dependency (for DOMNodesInserted events)
- Cleans up some JS workarounds & non-standard stuff

### CODE REVIEW

**Comment by micschk** [comment]
FIXED & tag release 0.1.3: ~Just found a small issue in SimplerSilverstripe with [DOMNodesInserted not being triggered *on form refresh after saving*](/restruct/silverstripe-simpler/issues/1) in the CMS, working on a fix~

All good to go!

**Comment by lekoala** [comment]
@micschk as discussed, i picked some of the parts of the pr to integrate them, but i'd rather keep simpler optional and keep the requirements options possible in the current state

**Comment by micschk** [comment]
(NOTE: after @lekoala and me discussing requirements bundling & the react-compatibility layer provided by SimplerSilverstripe on chat, I understand this module will stick with php Require calls & an extra JS file included in each ajax call instead (to trigger filepond init). Therefore closing this PR.)

**Comment by lekoala** [comment]
@micschk ;-) to be totally accurate, the module provides both ways (regular require calls or globally included files + simpler without any extra js file)

**Pull request closed without merging**
